CREATE DATABASE web_app_dev;

USE web_app_dev;

DROP TABLE video_data;

DROP TABLE artist_info;

SELECT * FROM video_data;

SELECT * FROM artist_info;

SELECT * FROM artist_info
INNER JOIN video_data
ON artist_info.artist  = video_data.artist;

-- ALTER TABLE video_data MODIFY COLUMN col VARCHAR(255)
-- CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

CREATE TABLE video_data (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SCRAPE_DATE DATE,
ARTIST VARCHAR(255) CHARACTER SET utf8,
PUBLISHED  DATE,
TITLE VARCHAR(255) CHARACTER SET utf8,
CATEGORY VARCHAR(255) CHARACTER SET utf8,
DURATION FLOAT,
VIEWS INT,
LIKES INT,
DISLIKES INT,
COMMENTS INT,
PAID VARCHAR(255) CHARACTER SET utf8,
FAMILY_FRIENDLY VARCHAR(255) CHARACTER SET utf8,
URL VARCHAR(255) CHARACTER SET utf8
);

CREATE TABLE artist_info(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SCRAPE_DATE DATE,
ARTIST VARCHAR(255) CHARACTER SET utf8,
JOINED DATE,
SUBSCRIBERS INT,
TOTAL_VIEWS INT
);

